---
- name: "Oci_Cloud Alert Remediation"
  hosts: all
  sources:
    - stevefulme1.oci_cloud.oci_events:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Critical alert
      condition: event.oci_cloud is defined
      action:
        run_playbook:
          name: remediate.yml
          extra_vars:
            alert: "{{ event.oci_cloud }}"
