---
- name: Validate
  ansible.builtin.assert:
    that: oci_iam_setup_compartment_id is defined
    quiet: true

- name: Execute oci iam setup
  ansible.builtin.debug:
    msg: "Configure compartments, groups, policies, and dynamic groups"
